### PR TITLE
Add "System default" to darkmode settings

### PR DESCRIPTION
**Pull request by beatbrot**
# Description

As discussed way back in #304, currently  the app is missing an option to follow the global setting for darkmode. This PR aims to fix this by introducing said option.

The change is rather large and hard to unit test so it would be nice if someone could look over it/test it on an emulator/device.

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
Nice!! That's indeed a big change. Maybe @korelstar or @dan0xii can review and test it, too?

I will need some time to review the changes.

**Comment by korelstar** [comment]
I'll try to do a review during this week ...

**Comment by stefan-niedermann** [comment]
Fresh install of the latest build:

1. Open app the very first time
2. Import account
3. Go to settings
4. See "System default" set
5. Change to "Light" - **crash**

```
App Version: 2.10.3
App Version Code: 81
Files App Version Code: 30100190

---

OS Version: 4.9.185-perf-g301928a(5d3e3c161a)
OS API Level: 28
Device: beryllium
Model (and Product): POCO F1 (beryllium)

---

java.lang.IllegalArgumentException: No enum constant it.niedermann.owncloud.notes.android.DarkModeSetting.Hell
	at java.lang.Enum.valueOf(Enum.java:258)
	at it.niedermann.owncloud.notes.android.DarkModeSetting.valueOf(DarkModeSetting.java:18)
	at it.niedermann.owncloud.notes.android.fragment.PreferencesFragment.lambda$onCreatePreferences$0$PreferencesFragment(PreferencesFragment.java:33)
	at it.niedermann.owncloud.notes.android.fragment.-$$Lambda$PreferencesFragment$8qg98-aBeAUBtVFGdlXTbTa_lhM.onPreferenceChange(Unknown Source:2)
	at androidx.preference.Preference.callChangeListener(Preference.java:1118)
	at androidx.preference.ListPreferenceDialogFragmentCompat.onDialogClosed(ListPreferenceDialogFragmentCompat.java:107)
	at androidx.preference.PreferenceDialogFragmentCompat.onDismiss(PreferenceDialogFragmentCompat.java:267)
	at androidx.fragment.app.DialogFragment$3.onDismiss(DialogFragment.java:116)
	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1393)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Comment by stefan-niedermann** [comment]
There seems to be an issue with the preference value - the value is translated (this is actually also in master the case as far as i know) - we should tackle this issue and migrate all currently translated theme *values* to a hard coded english string.

**Comment by beatbrot** [comment]
Seems like the ENUM Constant "LIGHT" was wrongfully translated to "Hell". This shouldn't happen. I should look into that.

Also, since the old setting was saved as an `boolean` in `SharedPreferences` and now has to be saved as String, we also need a migration method for that (since we use `SharedPreferences#getString(DARK_MODE, ...)` all over the place). I am not sure yet what a good solution for that might be...

**Comment by stefan-niedermann** [comment]
Oh, i messed this up with another setting.

Though yes, the value is translated and shouldn't.

The migration path from the previous boolean value seems to be pretty obvious to me:

- `true` -> dark theme
- `false` -> light theme
- unset -> system default

What do you think about using an fake database upgrade to migrate the values (an delete the previous boolean values from the shared preferences after the migration)?

**Comment by beatbrot** [comment]
I have to be honest, I never heard about the concept of a database upgrade :) I'd have to look into that.

**Comment by stefan-niedermann** [comment]
The idea is that a user with an very old .apk can easily upgrade without loosing all his settings and stuff, even if the tables changed.

You can have a look here: https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/java/it/niedermann/owncloud/notes/persistence/NoteSQLiteOpenHelper.java#L152

At some places in the `onUpgrade`-method we are already modifying shared preferences.

**Comment by beatbrot** [comment]
Ah, now I understand! We do not really do a database upgrade but instead fake one to get the chance to fix up SharedPreferences?

**Comment by beatbrot** [comment]
I added some migration logic for old users. Unforunately, the database migration happens after the first time the SharedPreferences are read. Therefore I still had to handle these cases :/

**Comment by beatbrot** [comment]
@korelstar I tried to incorporate your suggetions :) Maybe you can take another look at it?

**Comment by korelstar** [comment]
Thanks! A tiny optimization would be to move the definition of `DARK_THEME_KEY` to `NoteWidgetHelper` and to remove the parameter `darkModeKey` from `NoteWidgetHelper.getDarkThemeSetting`, since it's always the same (replace its usage with `DARK_THEME_KEY`).

**Comment by beatbrot** [comment]
@korelstar It actually is NOT always the same. In [SingleNoteWidget](https://github.com/stefan-niedermann/nextcloud-notes/blob/482be9b0931bc002086141a2dd4ae1c3bb6e069f/app/src/main/java/it/niedermann/owncloud/notes/android/appwidget/SingleNoteWidget.java#L37), it resolves to `SNW_darkTheme`, while it resolves to "NLW_darkTheme" in [NoteListWidgetFactory](https://github.com/stefan-niedermann/nextcloud-notes/blob/482be9b0931bc002086141a2dd4ae1c3bb6e069f/app/src/main/java/it/niedermann/owncloud/notes/android/appwidget/NoteListWidgetFactory.java#L39)

**Comment by korelstar** [comment]
Ah, okay. Then it's fine, of course! :-)

**Pull request merged**
