### PR TITLE
Single note widget

### PR DESCRIPTION
**Pull request by dan0xii**
First version of a single note widget as requested in https://github.com/stefan-niedermann/nextcloud-notes/issues/15.

### CODE REVIEW

**Comment by enoch85** [comment]
Do you have any screenshots?

**Comment by dan0xii** [comment]
https://github.com/dan0xii/nextcloud-notes/blob/widget_single_note/app/src/main/res/drawable/single_note_widget2.png

That's the preview image.

**Comment by korelstar** [comment]
Please squash your commits into a single one and then rebase the branch.
Unfortunately, I hadn't the time to look into this, but according to #241, this should be merged next :-)

**Comment by dan0xii** [comment]
I think I've sorted it now in PR https://github.com/stefan-niedermann/nextcloud-notes/pull/250. I'll close this.

**Pull request closed without merging**
