### PR TITLE
Fix the testInsertLink() function

### PR DESCRIPTION
**Pull request by Cui-Yusong**
Fix the testInsertLink() function, and the could pass all the TODO test.

### CODE REVIEW

**Review by stefan-niedermann — COMMENTED** [review]
Nice! I'll add a few more test cases for some edge cases (content is empty or contains only white spaces) because i feat that the `editable.charAt(...)` might lead to an exception in those cases after looping through via the `while` loop. But that's definitely a good start!

I will keep you updated.

**Comment by Cui-Yusong** [comment]
Wonderful! Looking forward to your furthur tests 😄

**Comment by stefan-niedermann** [comment]
Here are a few more tests for `insertLink` which should be passed.
- Don't worry, it looks more than it is. Some might already pass and most will work when checking for the bounds of the string at your `while` loops :wink: 
- It is **not important** if the assertions aren't matching *exactly*, feel free to adjust the expectations to something else which makes sense - they are edge cases after all.
- But it **is important** that the given test cases do not throw exceptions. (For example some of them will throw an `IndexOutOfBoundsException`).

```java
// TODO Add link without clipboardUrl to empty selection on empty text
builder = new SpannableStringBuilder("");
assertEquals(1, MarkdownUtil.insertLink(builder, 0, 0, null));
assertEquals("[]()", builder.toString());

// TODO Add link without clipboardUrl to empty selection on only space text
builder = new SpannableStringBuilder(" ");
assertEquals(2, MarkdownUtil.insertLink(builder, 0, 0, null));
assertEquals("[ ]()", builder.toString());

// TODO Add link without clipboardUrl to empty selection on only space text
builder = new SpannableStringBuilder(" ");
assertEquals(2, MarkdownUtil.insertLink(builder, 0, 1, null));
assertEquals("[ ]()", builder.toString());

// TODO Add link without clipboardUrl to empty selection on only space text
builder = new SpannableStringBuilder(" ");
assertEquals(1, MarkdownUtil.insertLink(builder, 1, 1, null));
assertEquals("[]()", builder.toString());

// TODO Add link without clipboardUrl to empty selection on only spaces
builder = new SpannableStringBuilder("  ");
assertEquals(2, MarkdownUtil.insertLink(builder, 1, 1, null));
assertEquals(" []() ", builder.toString());

// TODO Add link without clipboardUrl to empty selection in word with trailing and leading spaces
builder = new SpannableStringBuilder("  Lorem  ");
assertEquals(10, MarkdownUtil.insertLink(builder, 5, 5, null));
assertEquals("  [Lorem]()  ", builder.toString());

// TODO Add link with clipboardUrl to empty selection on empty text
builder = new SpannableStringBuilder("");
assertEquals(1, MarkdownUtil.insertLink(builder, 0, 0, "https://www.example.com"));
assertEquals("[](https://www.example.com)", builder.toString());

// TODO Add link with clipboardUrl to empty selection on only space text
builder = new SpannableStringBuilder(" ");
assertEquals(2, MarkdownUtil.insertLink(builder, 0, 0, "https://www.example.com"));
assertEquals("[ ](https://www.example.com)", builder.toString());

// TODO Add link with clipboardUrl to empty selection on only space text
builder = new SpannableStringBuilder(" ");
assertEquals(2, MarkdownUtil.insertLink(builder, 0, 1, "https://www.example.com"));
assertEquals("[ ](https://www.example.com)", builder.toString());

// TODO Add link with clipboardUrl to empty selection on only space text
builder = new SpannableStringBuilder(" ");
assertEquals(1, MarkdownUtil.insertLink(builder, 1, 1, "https://www.example.com"));
assertEquals("[](https://www.example.com)", builder.toString());

// TODO Add link with clipboardUrl to empty selection on only spaces
builder = new SpannableStringBuilder("  ");
assertEquals(2, MarkdownUtil.insertLink(builder, 1, 1, "https://www.example.com"));
assertEquals(" []() ", builder.toString());

// TODO Add link with clipboardUrl to empty selection in word with trailing and leading spaces
builder = new SpannableStringBuilder("  Lorem  ");
assertEquals(33, MarkdownUtil.insertLink(builder, 5, 5, "https://www.example.com"));
assertEquals("  [Lorem](https://www.example.com)  ", builder.toString());

// TODO Add link with clipboardUrl to selection in word with trailing and leading spaces
builder = new SpannableStringBuilder("  Lorem  ");
assertEquals(34, MarkdownUtil.insertLink(builder, 5, 8, "https://www.example.com"));
assertEquals("  [Lorem ](https://www.example.com) ", builder.toString());
```

**Comment by Cui-Yusong** [comment]
I made some changes in the new test to make it more logical.
Now the boundary conditions have been improved. 😄 
Please check if there are anything else I need to improve.

**Comment by stefan-niedermann** [comment]
Seems like something went wrong with the formatting... nearly all lines are marked in the diff, even if they haven't been touched. Could you please fix this?

**Comment by Cui-Yusong** [comment]
Of course.
Very sorry about the formatting. I will fix it soon.
Other than that,.ia there any other questions?

**Comment by Cui-Yusong** [comment]
Of course.
Very sorry about the formatting. I will fix it soon.
Other than that, is there any other questions?

**Comment by Cui-Yusong** [comment]
I've changed the formatting. Is there any other questions?

**Comment by stefan-niedermann** [comment]
Thank you :) No question at the moment, give me a day to make a review again but i'll guess we can merge it then 🙂

**Comment by stefan-niedermann** [comment]
Good job :slightly_smiling_face: 

I removed the `TODO`s from the comments, since they are now done.
Please avoid the `// CS304` comments - i guess this is your class or so? Your changes are in the [Git commit history](https://github.com/stefan-niedermann/nextcloud-notes/commits/master) and i will mention you in the release notes as authors of the changes.

**Pull request merged**
