### PR TITLE
#832 Move settings of NoteListWidget to Database

### PR DESCRIPTION
**Pull request by stefan-niedermann**
This one works pretty good already, but one thing seems to be defect now:

If one has multiple note list widgets on the screen they all display the same content (from the first selected category), while the titles are shown correctly. Also the data stored in the database is correct.

grafik

It think the information gets lost at some point between `NoteListWidget` (correct) and `NoteListWidgetFactory` (for each widget instance the same data - incorrect).

@dan0xii :innocent: :innocent: :innocent: :innocent:

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
Doh! Seems like i have removed too much. Will test your changes, thank you!

**Comment by dan0xii** [comment]
There's another issue where the category totals are all being displayed as zero in the configuration activity.

-------- Original Message --------

**Comment by dan0xii** [comment]
> There's another issue where the category totals are all being displayed as zero 
> in the configuration activity.

Fixed. Ready to test.

**Comment by stefan-niedermann** [comment]
Super! Thank you very much :) merged.

**Pull request merged**
