### PR TITLE
Rx markdown, Undo for "Swipe to delete", Nextcloud rebrand

### PR DESCRIPTION
**Pull request by stefan-niedermann**
#2 Render markdown inline
#147 Move from ownCloud to Nextcloud
#144 Undo for "Swipe to delete"

### CODE REVIEW

**Comment by korelstar** [comment]
Please note, that a release critical bug is still open: yydcdut/RxMarkdown#19.

**Comment by korelstar** [comment]
@stefan-niedermann 
Please be careful when using the *Squash and merge* functionality on a branch with commits from different authors. It seems that only the first author is retained. Due to this, the git log now shows you as the author of the changes I did in this branch. That's not so cool. Next time, please squash commits (of one author) manually (if necessary) and then perform a merge commit.

**Comment by stefan-niedermann** [comment]
I'm sorry, i wasn't aware of this. Maybe i have later some time to fix the git history - should be possible.
Be sure you will be prominently mentioned in all release notes :) (as soon as the critical rxmd bug has been fixed).
BTW i can not reproduce your issue with current master on my Nexus 5X. Create new note, type "Test", remove everything. Everything seems to be fine, am i missing something?
You are welcome to contact me directly via email or just have a call. my contact details are at my website.

**Comment by korelstar** [comment]
No need to be mentioned prominently, it was just about the logs, because that *could* be important sometime (although it's likely that it's not). :wink: 

I've sent you an e-mail ...

**Pull request merged**
