### PR TITLE
swipe to favorite

### PR DESCRIPTION
**Pull request by korelstar**
This branch was created by @stefan-niedermann.

I like the approach. After testing, I did a very small change and I think it's in a good state, now. However, there is still a discussion in #310, if this approach is sufficient. But with this PR, it's easier to track any changes on this.

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
@korelstar you might have read the commit commentar - do you have a good approach to change the background color based on the swipe-direction?

**Comment by korelstar** [comment]
No, I didn't read the comment at that point. But after your hint I provided a solution for the colors (see new commit in this branch). The type of yellow is not perfect, so please feel free to chose a better one (`colors.xml`).

**Comment by stefan-niedermann** [comment]
@jancborchardt can you help out with the color?

Background info: When swiping in the list from left to right, the background shall be yellow and as action the note is starred/unstarred instead of deleted.

When swiping from right to left the note gets still deleted (red background) - now we need an nice yellow color for starring/unstarring.

**Comment by jancborchardt** [comment]
The icons and colors are:
- Favorite: #ffcc00 https://github.com/nextcloud/server/blob/master/core/img/actions/starred.svg
- Delete: #d40000 https://github.com/nextcloud/server/blob/master/core/img/actions/delete-hover.svg

The icons should be white, which you can achieve by simply opening them up in a text editor and chaning the fill attribute to `fill="#fff"`. :)

**Pull request merged**
