### PR TITLE
refactor settings

### PR DESCRIPTION
**Pull request by schaarsc**
PR for #379 
- move cert settings to subscreen
- add icons
- remove categories

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
awesome :) thank you! :rocket:

**Comment by stefan-niedermann** [comment]
Nice work :)

- [ ] Make icons grey like in sidebar
- [ ] Is it possible that all list entries do have the same height whether or not they have a second line? (Account and certificates are currently smaller)
- [ ] Manage certificate does currently not show any top header bar, unlike account. It should have.
- [ ] The space between the icons and the text seems to be very big. is this some material standard or can we adjust it, so there is the same space like on the left side of the icons

device-2018-06-17-210853

**Comment by stefan-niedermann** [comment]
Hmm... i think it is fine for now if we let the certificate stuff as it is. Maybe, after #396 we can discuss it again? I don't want another PR depending on #396 because we already have #414 and i don't know when we can finally merge #396.

**Comment by korelstar** [comment]
That's fine.

**Comment by schaarsc** [comment]
- I'll change the color to grey if you want, but we could also use black for notnight and grey for night ...?
- the height depends on the second line, I'd suggest to stick to the standard
- I'd suggest to keep certificate mgmt page as is, until #418 is decided.
- we could use bigger icons, like in Android-Settings/Account?

**Comment by schaarsc** [comment]
image

Example to demonstrate some alternatives.
I'd choose bigger icon, notnight:blue, night:grey

Opinions?

**Comment by stefan-niedermann** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
The bigger icons seem ok – that also takes care of the whitespace being the same left and right.

But let’s use grey for both themes. Black on white is too extreme.

Very nice otherwise, good enhancement! :)

**Comment by korelstar** [comment]
> the height depends on the second line, I'd suggest to stick to the standard

I agree, but I propose to add a second line with explanatory text for all items.

For example:

- Account: Connect to your Nextcloud instance
- Server certificates: Manage special settings for transport layer security (TLS)

Your welcome to improve my text examples. :smiley:

**Comment by schaarsc** [comment]
notes

current impl with summary text. should I revert to only title?

**Comment by stefan-niedermann** [comment]
Much, much better :)

@jancborchardt i think personally i like the smaller icons more, but that's up to you. also: While the second line is not necessairy i think it helps to scan all options quicker because all entries do have the equal height...

**Comment by jancborchardt** [comment]
Looking at it now, I also think the smaller icons look better. It looks out of the ordinary on Android.

Equal lines don’t really help with scanning quicker if there’s more text to actually scan. ;) But more importantly: For display mode and theme, the second row actually shows relevant info – the current setting. With the additional text for account and certificates, the second row becomes irrelevant text which is probably not going to be read.

**Comment by schaarsc** [comment]
so the final decision is:
- small icons
- not text for cert / account
???

**Comment by jancborchardt** [comment]
@schaarsc yup! And, as @stefan-niedermann mentioned above:

> The space between the icons and the text seems to be very big. is this some material standard or can we adjust it, so there is the same space like on the left side of the icons

Then it would look much better.

**Comment by schaarsc** [comment]
I don't know if the space can be changed, the example on material.io look similar to our settings with 24dp icons https://material.io/design/platform-guidance/android-settings.html#placement

notes

an alternative are bigger icons e.g. 36dp icons (https://github.com/stefan-niedermann/nextcloud-notes/pull/417#issuecomment-398842121 was 48dp)
notes-medium

**Comment by stefan-niedermann** [comment]
Okay, let's go for the 24dp version for now :) looks great!

**Comment by korelstar** [comment]
The only difference to the examples on material.io is the icon's alignment.

In your PR, the icons are not exactly below the arrow of the ActionBar's back button. Fixing this could improve the overall impression.

From material.io:
image

**Comment by jancborchardt** [comment]
Yup – as @korelstar showed you only need to move them a bit to the right / center them.

If that’s done, we should go with the standard size icons – _not_ the bigger 36dp ones as they look strange.

**Comment by schaarsc** [comment]
there is no option to control the icon position 
https://developer.android.com/reference/android/preference/Preference

it is possible to modify the icon and add hard coded offset
notes
but this may look different if something is changed on the underlaying Preference implementation.

**Comment by korelstar** [comment]
Hmmm. No, that's dangerous. Maybe the icon size is not correct? How do other apps implement this?

I didn't found any app on my phone which has icons in it's preferences!

**Comment by jancborchardt** [comment]
Let’s go for this as first step. :) We can always adjust later, but for now we’re blocked by details. ;)

**Comment by stefan-niedermann** [comment]
I agree that modifying the hard icons with hardcoded offset is not a good idea. especially we can not estimate how this affects e. g. older android versions in combination with compat-libraries etc. etc. Though it is not perfect, we should go with the [version you posted here](https://github.com/stefan-niedermann/nextcloud-notes/pull/417#issuecomment-399847364) for now because it is way more stable and we do not have capacity to test each combination on every release:

version

@schaarsc can you please roll back to this version and resolve remaining conflicts? I will merge it then.

**Comment by schaarsc** [comment]
patch provided in #433

**Pull request closed without merging**
