### PR TITLE
#359 Use monospace font

### PR DESCRIPTION
**Pull request by stefan-niedermann**
Introduces a new setting and displays edit and view mode in monospace if it is set.

device-2018-08-23-150032
device-2018-08-23-150001
device-2018-08-23-150016

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
Ah, i think i get now the issue. But on the other hand: Is this really what we want? I think we want to provide a WYSIWYG-editor which renders as soon as you type. If we divide again in an source-edit-mode and a rendering-mode we will go the same way as so many other editors out there: a split-pane-mode. In an ideal world i would expect that we could get rid of the "view-mode" completely and only rely on an Edit-AND-View-mode. I think this would be a step back.

**Comment by DriverXX** [comment]
I think this is great, and it's enough for me, my request was simply to be able to use a monospace font.
That being said if you want really preserve the layout maybe you can consider to add a third "plain" view mode in which you do not use markdown.

**Comment by jancborchardt** [comment]
The setting should be called (with second detail line):

> Monospace font
> Used in editing view

And if enabled, the monospace font should be used only in editing view of course – not in the preview. :)

This then won’t change anything about the default experience, where the edit mode is the default and looks nice by default. This setting basically just fixes it for people where there’s a mess in edit mode.

**Comment by DriverXX** [comment]
> And if enabled, the monospace font should be used only in editing view of course – not in the preview. :)

I strongly disagree with this, why should we want a font change while changing view mode?
If I choose to use a monospace font I want it everywhere, I don't get your point on why we should have 2 different font for 2 different view mode

**Comment by jancborchardt** [comment]
@DriverXX ok, let’s do the monospace font for both views then. :) But by default the option is off.

**Pull request merged**
