### PR TITLE
WIP: #248 Refresh from server when in view mode

### PR DESCRIPTION
**Pull request by stefan-niedermann**
This PR basically works **but** whenever i set the new Content, it gets display but not rendered.

@korelstar any idea what might cause this behaviour?

Additionally: Currently this synchronizes all notes. Performance could be improved greatly if we only synchronize the current note.

### CODE REVIEW

**Comment by korelstar** [comment]
> This PR basically works but whenever i set the new Content, it gets display but not rendered.
>
> @korelstar any idea what might cause this behaviour?

This may be related to the problem in #427:

> After toggling a checkbox the content is displayed as plain text and does not get processed anymore

I have no idea how to fix this. Maybe you should report this to upstream (Rxmarkdown).

PS. I will try to do the requested reviews in the next days, but I can't promise ...

**Comment by stefan-niedermann** [comment]
https://github.com/yydcdut/RxMarkdown/issues/55

**Comment by stefan-niedermann** [comment]
Some updates here: It seems that if one does not use `JavaRx` but [the normal implementation](https://github.com/yydcdut/RxMarkdown/#non-rx-usage), that the rendering after setting new content works correctly.

**Comment by stefan-niedermann** [comment]
Aah, and yes. Toggling checkboxes seems to be possible with the normal implementation, too. It is currently active on this branch and i am happy if someone could help testing it.

@hanzei @rainerzufall @Offerel @jpggithub

**Pull request merged**
