### PR TITLE
Muety/enhancements and fixes

### PR DESCRIPTION
**Pull request by muety**
This PR addresses two issues.

# #920 
The issue here is view recycling, as explained [here](https://stackoverflow.com/a/33610194/3112139). My solution is a working quick fix. In the long run, the newly introduced [androidx.recyclerview:recyclerview-selection](https://developer.android.com/reference/androidx/recyclerview/selection/package-summary) package will probably be the proper solution, however, it requires [non-trivial refactoring](https://proandroiddev.com/a-guide-to-recyclerview-selection-3ed9f2381504).

# #949 
Nothing special here.

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
Thank you very much for the cobtributions! I'll have a look as soon as possible.

**Comment by muety** [comment]
Sure, no worries!

By the way, would you mind adding the _"Hacktoberfest"_ label (see [details](https://hacktoberfest.digitalocean.com/details#maintainers)) to this PR or to a few issues? I think this would encourage more open source enthusiasts, including me, to contribute to _nextcloud-notes_.

**Comment by stefan-niedermann** [comment]
Great contributions, thank you very much again and nice idea with the `TextProcessor` and `TextProcessorChain`.

> adding the "Hacktoberfest" label

Actually i think that [`Good first issue`](https://github.com/stefan-niedermann/nextcloud-notes/labels/Good%20first%20issue) and [`Help wanted`](https://github.com/stefan-niedermann/nextcloud-notes/labels/help%20wanted) labels are describing the intention better and are more generic. I'm also afraid of spam after a friend of mine got a victim of spam PRs. So, sorry, i will not add this label.

But if you share your PayPal adress to info@niedermann.it i can spend you a coffee for your contribution ☕ 😉

**Comment by muety** [comment]
Thanks for merging this.

> So, sorry, i will not add this label.

That's alright, I got your concerns.

> i can spend you a coffee for your contribution coffee

If you want check out my profile, there's a Buymeacoffee link :coffee: :wink: Also, I'm probably going to send you a bottle of the world's best beer :beer:

**Pull request merged**
