### PR TITLE
Added preference "Font Size".

### PR DESCRIPTION
**Pull request by keeshii**
The default font size is quite big, reading longer notes was troublesome. I decided to add an additional setting in the preferences. Now user can change the font size.

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
For reference: #276

The displayed font size depends on the system settings currently.

@jancborchardt do you think it is a needed option? It has been requested by 4 users until now.

**Comment by stefan-niedermann** [comment]
@keeshii thank you for the contribution, code-wise it looks very good. I will have a look about how it feels. While i declined a seperate setting for the font size in the past, i will reconsider it as the focus of the Notes app is on the texting and it might make sense.

**Comment by jancborchardt** [comment]
Right, the automatic font-size inheritance is a problem for accessibility here. So in this case a setting is fine. :)

@keeshii thank you for your contribution! Can you post a screenshot of the change for a quick design review?

**Comment by keeshii** [comment]
It's standard `ListPreference`. I had hard time deciding, which icon should I use. Finally I have selected the icon: [format_size](https://material.io/resources/icons/?icon=format_size&style=baseline).

Screenshot_20190808-062700_Notes
Screenshot_20190808-062715_Notes

**Comment by jancborchardt** [comment]
@keeshii nice! Icon and entry looks good. :+1:

Can you explain the sizes? I would have expected Small, Medium and Large, with "Medium" being the default.

**Comment by keeshii** [comment]
Sure.

At the beginning I was considering using the three options you mentioned: Small, Medium and Large. Such values are defined in the [TextAppearance](https://stackoverflow.com/a/11590581) resource of the android sdk. TextAppearance is using following sizes:
- Small = 14sp
- Medium = 18sp
- Large = 22sp

The unit "sp" means "scalled pixels". They represent the number of pixels, but the value is scalled by the DPI of the screen. The "sp" values are also affected by the font size setting in the system preferences, which makes it the best choice for defining the font sizes in the application.

I was playing a bit with those values on my phone. After a while I decided to use following options:
- Tiny = 14sp
- Small = 16sp
- Medium = 18sp
- Large = 22sp

14sp is quite small. Such size is good for captions on small UI elements, but not much for texting. Maybe on tables this size would be ok. I decided to leave this option as "Tiny".

Medium (18sp) is actually the system default. This size application was using before my MR. In my opinion it is big, so I put also something in between - 16sp.

... and Large is really Large. Good for old people.

**Comment by jancborchardt** [comment]
> 14sp is quite small. Such size is good for captions on small UI elements, but not much for texting.

Then I would just leave the "Tiny" option out. :)

3 options of Small, Medium and Large are very quick to understand, and "Medium" is going to be a good default. As soon as there’s another option, you don’t know anymore which is the inherent default and also as you said it’s quite small anyway.

What do you think @stefan-niedermann?

**Comment by stefan-niedermann** [comment]
Yes, i agree :)  @keeshii can you adjust the PR? :)

**Comment by keeshii** [comment]
> Yes, i agree :) @keeshii can you adjust the PR? :)

No problem. Done.

**Comment by stefan-niedermann** [comment]
Great, thank you for your contribution :) It might take some time until this will be released on Play Store because we usually are waiting for some translations via transifex (which might take some time).

**Comment by jancborchardt** [comment]
@keeshii welcome to Nextcloud Notes! :) More contributions are always very welcome!

**Pull request merged**
