### PR TITLE
#814 normalize database

### PR DESCRIPTION
**Pull request by Isaac-Graham**
I think I have finished all of the comments/requests left in the last pr. The CI also looks good so that I think it is time to submit a new pr to merge into master.

Some new update: 
1) Add `@NonNull` annotation in the Capabilities.
2) Add unique over category_account_id and category_title
3) Persist the capabilities value in `addAccount`
4) Remove the random test for the fixed test is enough

Please help me review it.

### CODE REVIEW

**Comment by Isaac-Graham** [comment]
Thanks for testing. I am busy these days. Will fix this weekend. Is there any other bugs?

**Comment by stefan-niedermann** [comment]
Haven't found any yet, but i will continue testing of course :)

**Comment by korelstar** [comment]
Is there any difference between this PR and the old PR (#815)?

**Comment by Isaac-Graham** [comment]
> Is there any difference between this PR and the old PR (#815)?

Just some very small changes. 

1) Merge codes with the latest `AbstractDatabases.java` which has been updated after I started to refactor the database.
2) Add `@Nonnull` in the constructor for response in the constructor in Capabilities
3) Fix CI error. The reason for CI error is that in the latest `AbstractDatabases.java`, the interface of `addAccount()` method has been changed. But this method was called in the test files written by us with the old interface. So that CI error in running unit test.
4) A random test in test files is unneeded and we remove it from test files.

**Comment by Isaac-Graham** [comment]
BTW, I am busy in intern now. So that the progress may be slow. Do not worry. I will take time out to do the request.

**Pull request merged**
