### PR TITLE
enable code shrinking

### PR DESCRIPTION
**Pull request by connyduck**
closes https://github.com/stefan-niedermann/nextcloud-notes/issues/1119

This configuration does not obfuscate the bytecode so stacktraces will still be readable. It does some other useful things like removing unused code.

This reduces the size of the app-fdroid-release.apk from 6.964kB to 5.342kB (-23%). With obfuscation it would be 3.949kB (-43%).

(I understand why somebody would not like to use obfuscation, but fyi Google Play deofuscates stacktraces automatically if you use appbundles and you can also do it manually with the retrace tool if you save the optimization.txt files from release builds)

Btw, thank you for this cool app, I use it a lot. :relaxed:

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
Thank you for the contribution :rocket:

It looks like the `CustomAppGlideModule` isn't available (or working) anymore, at least the account avatar is not longer shown. Can you confirm this?

I really appreciate all the efforts, but i have doubts that it's worth when getting an unpredictable and unreliable `.apk` file in the end which behaves different and in ways and corners which aren't really on our radar. After all it is downloaded *once* and updates can be scheduled. It's more critical for websites which will load the app on every usage (if no service workers are used at least).

Regarding app bundles: I am aware of the benefits, but my last state was that one needs to put the private signing key to Play Store if one wants to use it and is not able to build *and* sign the bundle locally and publish it then... (that is a no-go of course, why i didn't do more research regarding this topic)

**Comment by connyduck** [comment]
> It looks like the CustomAppGlideModule isn't available (or working) anymore, at least the account avatar is not longer shown. Can you confirm this?

My bad. Fixed.

> I really appreciate all the efforts, but i have doubts that it's worth when getting an unpredictable and unreliable .apk file in the end which behaves different and in ways and corners which aren't really on our radar. 

I maintain several heavily shrinked apps and never had such problems. The key is to test release builds extensively before releasing them, because they may differ from debug builds. But I understand if that is too much overhead for you.

> Regarding app bundles: I am aware of the benefits, but my last state was that one needs to put the private signing key to Play Store if one wants to use it and is not able to build and sign the bundle locally and publish it then... (that is a no-go of course, why i didn't do more research regarding this topic)

I have bad news for you: Google will make App Bundles mandatory at the and of this year.

**Comment by stefan-niedermann** [comment]
> My bad. Fixed.

Thanks 🙂 

> The key is to test release builds extensively before releasing them, because they may differ from debug builds.

I got that, but i don't have the resoueces to completely test every feature before every release. Even with automated tests would beed to run against release builds (this should be possible i guess).

Let me think about it and please don't take it as offense if i don't merge the changes. The trade-off is quite high.

> I have bad news for you: Google will make App Bundles mandatory at the and of this year.

Heard that 🙁  Still hoping for some kind of opt-out...

**Comment by stefan-niedermann** [comment]
Did you forget to push your glide fix? I can't see another commit yet and the files look the same 🤷‍♂️ ...

**Comment by stefan-niedermann** [comment]
Sorry, i consider the risc being too high (at least with the current resources for this project). Something slipping through will be quite dangerous and recognized too late by me.

I really appreciate the effort you put into this and i would like to invite you to join #1036 which will be capable of reducing the final app size, too (by removing a complete dependency), but the minification topic is currently out of my scope.

Thank you & regards

**Pull request closed without merging**
