### PR TITLE
Fix rotation

### PR DESCRIPTION
**Pull request by schaarsc**
suggested fix for #252

### CODE REVIEW

**Comment by korelstar** [comment]
Please wait before merging this. I would like to review this in detail in the next days.

**Comment by stefan-niedermann** [comment]
Feel free to merge it yourself if you agree to the changes :)

**Comment by korelstar** [comment]
I see still some issues with the code. But since this doesn't concerns this PR in particular and this PR  fixes and important issue, I'm merging it now. Nevertheless, please note the extended list of issues in #246 :-)

**Comment by stefan-niedermann** [comment]
:+1:

**Pull request merged**
