### PR TITLE
Merge activities

### PR DESCRIPTION
**Pull request by schaarsc**
implements #155 #217 

this PR is based on #213 because I wanted to use the new Preferences.

I'd suggest to keep CreateNoteActitvity as separate Activity, because it does not fit well into the new EditNoteActitvity (no auto-save, different ActionBar, different return Intent)

The workflow is implemented as global preference. It should be no problem to add per note option, should  this be required at a later point of time.

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
I'll check this in two weeks, i'm on vacation. Thanks for the work.
One hint: It should not be implemented as a preference but simply stored whenever the user toggles the state.

**Comment by schaarsc** [comment]
how do you want to proceed with this PR? This is a big change it already has conflicts and it will only get worse...

**Comment by korelstar** [comment]
@schaarsc Please rebase your branch in order to get rid of the several commits which already has been merged to `master`.

**Comment by schaarsc** [comment]
see #242

**Pull request closed without merging**
