### PR TITLE
trying to solve issue #199

### PR DESCRIPTION
**Pull request by fabienli**

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
Great that you are able to contribute here! Keep us up to date so we may can help and or review your fix. :)

cc @korelstar

**Comment by stefan-niedermann** [comment]
@fabienli ready to test?

**Comment by stefan-niedermann** [comment]
@korelstar so you are suggesting that we remove all `db.close()` calls?
You explained the effect is the same, i see. I am fine with both variants. If you want to create a separate pull request with the proposed changes i will merge it, otherwise i will merge this PR. Anyway, this issue is annoying and i want to get rid of it.

**Comment by korelstar** [comment]
Yes, I suggest to remove that. I will create a PR soon.

**Comment by stefan-niedermann** [comment]
Fixed with #212. Thank you very much @fabienli for bringing us on the track :) 👍

**Pull request closed without merging**
